name: stylesage
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

#--------------packages------------------#
dependencies:
  flutter:
    sdk: flutter


  #icons 
  cupertino_icons: ^1.0.2

  #utility packages
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  multiselect_dropdown_flutter: ^0.0.7
  url_launcher: ^6.2.5
  lottie: ^3.1.0
  connectivity_plus: ^6.0.3
  flutter_native_splash: ^2.3.10
  #url_launcher
  #intl
  #http
  #logger


  #state Management
  get: ^4.6.6
  get_storage: ^2.1.1
 
  

  #firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/icons/appointmentCardVendor/
    - assets/icons/services/
    - assets/icons/profile/
    - assets/icons/navigation_menu/
    - assets/images/
    - assets/images/appointment/
    - assets/images/payment/
    - assets/images/services/
    - assets/images/onboarding/
    - assets/images/banners/
    - assets/images/profile/
    - assets/logos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
