// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmfOoTKNrLCZBwptNuy3pB8cczsVeGnNQ',
    appId: '1:760968111277:android:99442503580fb3124d5224',
    messagingSenderId: '760968111277',
    projectId: 'fyp-stylesage',
    storageBucket: 'fyp-stylesage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn7NlrGvWTl0qOcWn6j-GJVTh_rbkF9A4',
    appId: '1:760968111277:ios:076f11d2b5c8e42d4d5224',
    messagingSenderId: '760968111277',
    projectId: 'fyp-stylesage',
    storageBucket: 'fyp-stylesage.appspot.com',
    androidClientId: '760968111277-u3mph37l7ln0br6jj55tmnddc398i1ib.apps.googleusercontent.com',
    iosClientId: '760968111277-gsv6n2835a0euumhc8744lln4ll80cdr.apps.googleusercontent.com',
    iosBundleId: 'com.example.stylesage',
  );

}